sequenceDiagram
    autonumber
    actor User as  User (React)
    participant API as  Spring Boot (Backend)
    participant DB as  MySQL Database
    participant AI as  AI Service (Python)

    Note over User, API: 1. User initiates Transfer
    User->>API: POST /transfer {receiver, amount}

    activate API

    Note right of API: Step 1: Validation & Balance Check
    API->>DB: Select Wallet (Sender)
    DB-->>API: Return Wallet Data + Balance

    alt Insufficient Balance
        API-->>User: Error: Insufficient Funds
    else Balance OK

        Note right of API: Step 2: Fraud Detection (Integration)
        API->>API: Map Data to FraudCheckRequest
        API->>AI: POST /predict-fraud (amount, time, history)

        activate AI
        AI-->>API: Return { isFraud: boolean }
        deactivate AI

        alt Fraud Detected
            API->>DB: Log Attempt as "BLOCKED"
            API-->>User: Error: Transaction Suspicious!
        else Safe Transaction

            Note right of API: Step 3: Atomic Transaction
            API->>DB: Begin Transaction
            API->>DB: Update Sender Balance (-)
            API->>DB: Update Receiver Balance (+)
            API->>DB: Save Transaction Record
            DB-->>API: Commit Success

            API-->>User: Success: Transfer Complete
        end
    end
    deactivate API